[connections.supabase]
SUPABASE_URL = "https://owctcbqmjjdnvffzqaup.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93Y3RjYnFtampkbnZmZnpxYXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjgzNTc3NDQsImV4cCI6MjA0MzkzMzc0NH0.uTGbO3dtpkjsvQUC6A7v1O_d3guIC6l-ApxtmZSlSdQ"
